language: go

go:
  - 1.3
  - 1.4

before_install:
  - go get -u github.com/golang/lint/golint
  - if [[ $TRAVIS_GO_VERSION == 1.5* ]]; then go get -u github.com/kisielk/errcheck; fi

before_script:
  - '! gofmt -s -l . | read'
  - golint ./...
  - echo $TRAVIS_GO_VERSION
  - if [[ $TRAVIS_GO_VERSION == 1.5* ]]; then errcheck ./...; fi
